# Generated by Django 4.2.11 on 2024-03-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Todos',
        ),
    ]
